### ISSUE TITLE
The API throws an error when no options and only callback is provided

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-sdk-for-node#1050]
The API does not take into consideration that optionsOrCallback is optional and one can directly provide a callback. The newly generated code is doing the validation incorrectly.

```
blobService.createBlockBlobFromStream(
    containerName, 
    blockblobName, 
    stream,
    len, //{} <-- If I provide an empty object then it works perfectly fine. This is a breaking change to the API
    function (error, result) {
        if (error) {
            var bytes1 = blobService.writeBlockSizeInBytes;
            console.log('chunk size: ' + bytes1);
            console.log(error);
        }
        else {
            console.log(result);
            console.log('blockblob with 64M uploaded successfully');
            var bytes1 = blobService.writeBlockSizeInBytes;
            console.log('chunk size: ' + bytes1);   
        }
    }
);
```

I get the following error:

```
D:\test\amarnodetest\node-0.7.17\azure-sdk-for-node\lib\util\validate.js:418
  throw new Error('Required argument ' + name + ' for function ' + func + ' is
        ^
Error: Required argument callback for function createBlockBlobFromStream is not defined
    at throwMissingArgument (D:\test\amarnodetest\node-0.7.17\azure-sdk-for-node\lib\util\validate.js:418:9)
    at ArgumentValidator._.extend.object (D:\test\amarnodetest\node-0.7.17\azure-sdk-for-node\lib\util\validate.js:434:7)
    at ArgumentValidator._.extend.callback (D:\test\amarnodetest\node-0.7.17\azure-sdk-for-node\lib\util\validate.js:461:10)
    at D:\test\amarnodetest\node-0.7.17\azure-sdk-for-node\lib\services\blob\blobservice.js:2702:7
    at Object.validateArgs (D:\test\amarnodetest\node-0.7.17\azure-sdk-for-node\lib\util\validate.js:480:3)
    at BlobService.createBlockBlobFromStream (D:\test\amarnodetest\node-0.7.17\azure-sdk-for-node\lib\services\blob\blobservice.js:2697:12)
    at Object.<anonymous> (D:\test\amarnodetest\node-0.7.17\scenario_tests\storage-test.js:51:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

D:\test\amarnodetest\node-0.7.17\scenario_tests>
```

**Comment by piyush-dholariya** [comment]
Still I am getting this error over here.

**Comment by amarzavery** [comment]
The storage sdk for dataplane in this repo is legacy sdk. The source code has moved to a new repo https://github.com/Azure/azure-storage-node.

**Comment by DaveVoyles** [comment]
I'm still getting this same issue.

 ```javascript
    blobService.createBlockBlobFromStream(sContainer, "myName.png", stream, stream.length, function(error) {
        if (error){
            log(error);}
        }
    );
```

**Error:**
```
  throw new ArgumentNullError(name, 'Required argument ' + name + ' for function ' + func + ' is not defined');
````

Version:    "azure-storage": "^2.1.0",

**Comment by amarzavery** [comment]
@hasonmsft - Can you take a look at this issue as well?

**Comment by hasonmsft** [comment]
@XiaoningLiu, could you take a look this this?
