### ISSUE TITLE
deployment on Azure generates "Error: Access to the path 'bson.node' is denied."

### ISSUE THREAD

**Issue by Abdelkrim** [Azure/azure-sdk-for-node#1178]
The local tests passed then I deployed through GIT the source code using &quot;git push&quot;.

I received the following error **&quot;Error: Access to the path 'bson.node' is denied.&quot;**

How could I circumvent this error ?

Thanks in advance,

2011-12-15T11:33:41    Deleting directory: 'node_modules\mongoskin\lib'
2011-12-15T11:33:41    Deleting file: 'node_modules\mongoskin\node_modules\mongodb.travis.yml'
2011-12-15T11:33:41    Deleting file: 'node_modules\mongoskin\node_modules\mongodb\CONTRIBUTING.md'
2011-12-15T11:33:41    Deleting file: 'node_modules\mongoskin\node_modules\mongodb\index.js'
2011-12-15T11:33:41    Deleting file: 'node_modules\mongoskin\node_modules\mongodb\LICENSE'
2011-12-15T11:33:41    Deleting file: 'node_modules\mongoskin\node_modules\mongodb\Makefile'
2011-12-15T11:33:41    Deleting file: 'node_modules\mongoskin\node_modules\mongodb\package.json'
2011-12-15T11:33:41    Deleting file: 'node_modules\mongoskin\node_modules\mongodb\Readme.md'
2011-12-15T11:33:41    Deleting file: 'node_modules\mongoskin\node_modules\mongodb\t.js'
2011-12-15T11:33:41    Deleting file: 'node_modules\mongoskin\node_modules\mongodb\lib\mongodb\admin.js'
2011-12-15T11:33:41    Omitting next output lines...
2011-12-15T11:33:42    Error: Access to the path 'bson.node' is denied.
2011-12-15T11:33:42    Failed exitCode=1, command=&quot;kudusync&quot; -v 50 -f &quot;D:\home\site\repository&quot; -t &quot;D:\home\site\wwwroot&quot; -n &quot;D:\home\site\deployments\LJHLKJLKJH\manifest&quot; -p &quot;D:\home\site\deployments\LJHLKJLKJH987\manifest&quot; -i &quot;.git;.hg;.deployment;deploy.cmd&quot;
2011-12-15T11:33:42    An error has occurred during web site deployment.
2011-12-15T11:33:42            Error occurred, type: error, text: Error: Access to the path 'bson.node' is denied.
D:\Program Files (x86)\SiteExtensions\Kudu\1.5.36.68\bin\scripts\starter.cmd D:\home\site\deployments\tools\deploy.cmd, stackTrace:    at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args)
   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args)
   at Kudu.Core.Deployment.Generator.ExternalCommandBuilder.RunCommand(DeploymentContext context, String command)
2011-12-15T11:33:42  
2011-12-15T11:33:43          Error occurred, type: error, text: Error: Access to the path 'bson.node' is denied.
D:\Program Files (x86)\SiteExtensions\Kudu\1.5.36.68\bin\scripts\starter.cmd D:\home\site\deployments\tools\deploy.cmd, stackTrace:    at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args)
   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args)
   at Kudu.Core.Deployment.Generator.ExternalCommandBuilder.RunCommand(DeploymentContext context, String command)
   at Kudu.Core.Deployment.Generator.GeneratorSiteBuilder.Build(DeploymentContext context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Kudu.Core.Deployment.DeploymentManager.d__29.MoveNext()
2011-12-15T11:33:44  Fetching changes.
2011-12-15T11:33:47  Updating submodules.
2011-12-15T11:33:47  Preparing deployment for commit id 'LJHUYG987'.
2011-12-15T11:33:48  Generating deployment script.
2011-12-15T11:33:48    Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r &quot;D:\home\site\repository&quot; -o &quot;D:\home\site\deployments\tools&quot; --node --sitePath &quot;D:\home\site\repository&quot;').
2011-12-15T11:33:48  Running deployment command...
2011-12-15T11:33:48    Command: D:\home\site\deployments\tools\deploy.cmd
2011-12-15T11:33:48    Handling node.js deployment.
2011-12-15T11:33:49    KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
2011-12-15T11:33:49    Error: Access to the path 'bson.node' is denied.
2011-12-15T11:33:49    Deleting file: 'node_modules\mongoskin\node_modules\mongodb\node_modules\bson\ext\win32\ia32\bson.node'
2011-12-15T11:33:49    Failed exitCode=1, command=&quot;kudusync&quot; -v 50 -f &quot;D:\home\site\repository&quot; -t &quot;D:\home\site\wwwroot&quot; -n &quot;D:\home\site\deployments\LJHLKJLKJH\manifest&quot; -p &quot;D:\home\site\deployments\LJHLKJLKJH987\manifest&quot; -i &quot;.git;.hg;.deployment;deploy.cmd&quot;
2011-12-15T11:33:49    An error has occurred during web site deployment.
2011-12-15T11:33:49            Error occurred, type: error, text: Error: Access to the path 'bson.node' is denied.
D:\Program Files (x86)\SiteExtensions\Kudu\1.5.36.68\bin\scripts\starter.cmd D:\home\site\deployments\tools\deploy.cmd, stackTrace:    at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args)
   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args)
   at Kudu.Core.Deployment.Generator.ExternalCommandBuilder.RunCommand(DeploymentContext context, String command)
2011-12-15T11:33:49  
2011-12-15T11:33:49          Error occurred, type: error, text: Error: Access to the path 'bson.node' is denied.
D:\Program Files (x86)\SiteExtensions\Kudu\1.5.36.68\bin\scripts\starter.cmd D:\home\site\deployments\tools\deploy.cmd, stackTrace:    at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args)
   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args)
   at Kudu.Core.Deployment.Generator.ExternalCommandBuilder.RunCommand(DeploymentContext context, String command)
   at Kudu.Core.Deployment.Generator.GeneratorSiteBuilder.Build(DeploymentContext context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Kudu.Core.Deployment.DeploymentManager.d__29.MoveNext()<p><a href="https://github.com/Azure/azure-sdk-for-node/issues/1178">https://github.com/Azure/azure-sdk-for-node/issues/1178</a></p>

**Comment by johnwp** [comment]
Did anyone come across a fix for this? This seems to have started after installing connect-mongo. I wonder if active browser sessions are preventing the connection to MongoDB from being closed for some reason. I haven't seen this problem in a similarly-configured Azure/MongoDB/Mongoose environment.

**Comment by johnwp** [comment]
Adding <EnableMSDeployAppOffline>true</EnableMSDeployAppOffline> doesn't seem to have any effect.
