### ISSUE TITLE
RoleEnvironment.isAvailable is callback-ed twice

### ISSUE THREAD

**Issue by compulim** [Azure/azure-sdk-for-node#1302]
I am running Node v0.10.25 with azure-sdk-for-node 0.9.15 (I did "npm install" about 22 hours ago). I deployed the code to Azure Worker Role of OS family 4 (Windows 2012 R2) latest.

At initialization stage of my code, I called `RoleEnvironment.isAvailable()` and waited until the Azure SDK is available before initializing my other code.

The `isAvailable()` call failed with callback with `EPIPE` (details below), but the callback on `isAvailable()` is being invoked again as successful (about 100ms later). I double-checked that I have only invoked `isAvailable()` once but got two callbacks. Here is the stack trace:

First callback, which result in an `EPIPE` error:
```
    at C:\worker\server.js:83:72
    at C:\worker\node_modules\azure\lib\serviceruntime\roleenvironment.js:217:7
    at C:\worker\node_modules\azure\lib\serviceruntime\roleenvironment.js:484:9
    at C:\worker\node_modules\azure\lib\serviceruntime\runtimeversionmanager.js:46:7
    at C:\worker\node_modules\azure\lib\serviceruntime\runtimeversionprotocolclient.js:32:7
    at callbackError (C:\worker\node_modules\azure\lib\serviceruntime\namedpipeinputchannel.js:29:5)
    at C:\worker\node_modules\azure\lib\serviceruntime\namedpipeinputchannel.js:34:14
    at Socket.<anonymous> (C:\worker\node_modules\azure\lib\serviceruntime\namedpipeinputchannel.js:79:5)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
```

Second callback from a single `isAvailable()` call, which should not happen. The result of the callback is positive.
```
    at C:\worker\server.js:83:72
    at C:\worker\node_modules\azure\lib\serviceruntime\roleenvironment.js:217:7
    at C:\worker\node_modules\azure\lib\serviceruntime\roleenvironment.js:469:9
    at C:\worker\node_modules\azure\lib\serviceruntime\protocol1runtimegoalstateclient.js:61:13
    at C:\worker\node_modules\azure\lib\serviceruntime\fileinputchannel.js:36:7
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
```

And the error `EPIPE` during the first callback fail
```
{
  "err": {
    "message": "shutdown EPIPE",
    "code": "EPIPE",
    "stack": "Error: shutdown EPIPE\n    at errnoException (net.js:901:11)\n    at Socket.onSocketFinish (net.js:217:26)\n    at Socket.EventEmitter.emit (events.js:92:17)\n    at finishMaybe (_stream_writable.js:356:12)\n    at endWritable (_stream_writable.js:363:3)\n    at Socket.Writable.end (_stream_writable.js:341:5)\n    at Socket.end (net.js:397:31)\n    at Socket.<anonymous> (C:\\worker\\node_modules\\azure\\lib\\serviceruntime\\namedpipeinputchannel.js:72:19)\n    at Socket.EventEmitter.emit (events.js:95:17)\n    at Socket.<anonymous> (_stream_readable.js:746:14)"
  }
}
```

Subsequent calls to `isAvailable()` will result in success and never invoke the callback more than once. FYI, here is the stack trace for my second `isAvailable()` callback.

```
    at C:\worker\server.js:83:72
    at C:\worker\node_modules\azure\lib\serviceruntime\roleenvironment.js:217:7
    at C:\worker\node_modules\azure\lib\serviceruntime\roleenvironment.js:469:9
    at C:\worker\node_modules\azure\lib\serviceruntime\protocol1runtimegoalstateclient.js:67:9
    at Protocol1RuntimeGoalStateClient._ensureGoalStateRetrieved (C:\worker\node_modules\azure\lib\serviceruntime\protocol1runtimegoalstateclient.js:79:5)
    at Protocol1RuntimeGoalStateClient.getRoleEnvironmentData (C:\worker\node_modules\azure\lib\serviceruntime\protocol1runtimegoalstateclient.js:55:8)
    at Protocol1RuntimeClient.getRoleEnvironmentData (C:\worker\node_modules\azure\lib\serviceruntime\protocol1runtimeclient.js:47:24)
    at getCurrentEnvironmentData (C:\worker\node_modules\azure\lib\serviceruntime\roleenvironment.js:464:35)
    at C:\worker\node_modules\azure\lib\serviceruntime\roleenvironment.js:458:9
    at C:\worker\node_modules\azure\lib\serviceruntime\protocol1runtimegoalstateclient.js:46:7
```

p.s. Although the `EPIPE` error is not the primary reason of this bug, I suspect I got `EPIPE` because I just upgrade the package and there are open handle issues/behaviors in the Azure Bootstrapper.

**Comment by amarzavery** [comment]
Closing this issue due to age. Feel free to open it if required.
