### ISSUE TITLE
can't create hdinsight config

### ISSUE THREAD

**Issue by clackner2007** [Azure/azure-sdk-for-node#1577]
I'm using the arm mode to create a configuration file for hdinsight cluster deployment. I'm following the instructions [here](https://azure.microsoft.com/en-us/documentation/articles/hdinsight-hadoop-create-windows-clusters-cli/). When I run `azure hdinsight config create myconf.config` I get the following error about not being able to get the 'subscription' property.

```{ [TypeError: Cannot read property 'subscription' of undefined]
  stack: [Getter/Setter],
  __frame: 
   { name: 'createClusterConfigCommand__10',
     line: 513,
     file: '/opt/local/lib/node_modules/azure-cli/lib/commands/arm/hdinsight/hdinsight.js',
     prev: 
      { name: '__10',
        line: 709,
        file: '/opt/local/lib/node_modules/azure-cli/lib/commands/arm/hdinsight/hdinsight.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 1,
        col: 11 },
     calls: 1,
     active: true,
     offset: 1,
     col: 31 },
  rawStack: [Getter] }
TypeError: Cannot read property 'subscription' of undefined
  <<< async stack >>>
  at createClusterConfigCommand__10 (/opt/local/lib/node_modules/azure-cli/lib/commands/arm/hdinsight/hdinsight.js:514:32)
  at __10 (/opt/local/lib/node_modules/azure-cli/lib/commands/arm/hdinsight/hdinsight.js:710:12)
  <<< raw stack >>>
    at createConfigFile (/opt/local/lib/node_modules/azure-cli/lib/commands/arm/hdinsight/hdinsight.js:191:54)
    at ___ (/opt/local/lib/node_modules/azure-cli/lib/commands/arm/hdinsight/hdinsight.js:525:26)
    at ___ (/opt/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/opt/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/opt/local/lib/node_modules/azure-cli/lib/util/interaction.js:217:20)
    at ___ (/opt/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at /opt/local/lib/node_modules/azure-cli/lib/util/interaction.js:174:7
    at ReadStream.<anonymous> (/opt/local/lib/node_modules/azure-cli/node_modules/commander/lib/commander.js:763:5)
    at ReadStream.g (events.js:260:16)
    at emitOne (events.js:77:13)```


I'm using the 0.9.13 version on OSX. I'm sure I have the subscription correct as other commands (i.e. `azure hdinsight cluster list`, etc.) all work fine.
<!---@tfsbridge:{"tfsId":5534800}-->

**Comment by amarzavery** [comment]
@clackner2007 This is an issue with azure-xplat-cli. I am opening this in the right repository for you. Here is the link to the issue https://github.com/Azure/azure-xplat-cli/issues/2515
