### ISSUE TITLE
roleenvironment-tests getLocalResourcesNoGoalStateNamedPipe fails with TypeError: block must be a function

### ISSUE THREAD

**Issue by peterblazejewicz** [Azure/azure-sdk-for-node#1586]
When running project tests I receive:

```
484 passing (8s)
  4 pending
  1 failing

  1) roleenvironment-tests getLocalResourcesNoGoalStateNamedPipe:
     TypeError: block must be a function
      at Function._throws (assert.js:288:11)
      at Function.assert.throws (assert.js:323:11)
      at Context.<anonymous> (/Users/piotrblazejewicz/git/azure-sdk-for-node/test/serviceruntime/roleenvironment-tests.js:198:12)
      at Test.Runnable.run (/Users/piotrblazejewicz/git/azure-sdk-for-node/node_modules/mocha/lib/runnable.js:204:15)
      at Runner.runTest (/Users/piotrblazejewicz/git/azure-sdk-for-node/node_modules/mocha/lib/runner.js:378:10)
      at /Users/piotrblazejewicz/git/azure-sdk-for-node/node_modules/mocha/lib/runner.js:456:12
      at next (/Users/piotrblazejewicz/git/azure-sdk-for-node/node_modules/mocha/lib/runner.js:303:14)
      at /Users/piotrblazejewicz/git/azure-sdk-for-node/node_modules/mocha/lib/runner.js:313:7
      at next (/Users/piotrblazejewicz/git/azure-sdk-for-node/node_modules/mocha/lib/runner.js:251:23)
      at /Users/piotrblazejewicz/git/azure-sdk-for-node/node_modules/mocha/lib/runner.js:275:7
      at done (/Users/piotrblazejewicz/git/azure-sdk-for-node/node_modules/mocha/lib/runnable.js:195:5)
      at /Users/piotrblazejewicz/git/azure-sdk-for-node/node_modules/mocha/lib/runnable.js:207:9
      at Context.<anonymous> (/Users/piotrblazejewicz/git/azure-sdk-for-node/test/serviceruntime/roleenvironment-tests.js:92:5)
      at Hook.Runnable.run (/Users/piotrblazejewicz/git/azure-sdk-for-node/node_modules/mocha/lib/runnable.js:204:15)
      at next (/Users/piotrblazejewicz/git/azure-sdk-for-node/node_modules/mocha/lib/runner.js:263:10)
      at Immediate._onImmediate (/Users/piotrblazejewicz/git/azure-sdk-for-node/node_modules/mocha/lib/runner.js:280:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Is that expected because of my environment (Mac/_nix, OS X 10.10._, Node 4.2.4 LST)?
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/serviceruntime/roleenvironment.js#L34-L35

```
* __Note__: RoleEnvironment will only work if your code is running in a worker role
* inside the Azure emulator or in a Microsoft Azure Cloud Service!
```

**Comment by amarzavery** [comment]
I am not sure about this. May be the websites team will be able to respond on this.
@ahmedelnably - Can you take a look at this issue?
