### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by benjsicam** [Azure/azure-sdk-for-node#1719]
When instantiating a new NetworkManagementClient from azure-arm-network, I encounter this error.

```
/Users/user/azuretest/node_modules/underscore/underscore.js:777
    var keys = _.keys(obj);
                 ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Function._.values (/Users/user/azuretest/node_modules/underscore/underscore.js:777:18)
    at exports.createWithSink (/Users/user/azuretest/node_modules/azure-arm-network/node_modules/ms-rest/lib/requestPipeline.js:52:17)
    at Object.<anonymous> (/Users/user/azuretest/node_modules/azure-arm-network/node_modules/ms-rest/lib/requestPipeline.js:149:35)
    at NetworkManagementClient.ServiceClient (/Users/user/azuretest/node_modules/azure-arm-network/node_modules/ms-rest/lib/serviceClient.js:57:66)
    at NetworkManagementClient.AzureServiceClient (/Users/user/azuretest/node_modules/azure-arm-network/node_modules/ms-rest-azure/lib/azureServiceClient.js:36:32)
    at new NetworkManagementClient (/Users/user/azuretest/node_modules/azure-arm-network/lib/networkManagementClient.js:69:37)
    at async.waterfall.networkMngmtClient.publicIPAddresses.createOrUpdate.location (/Users/user/azuretest/networkTest.js:27:28)
```

**Comment by benjsicam** [comment]
My code is:

```javascript
var async                   = require('async'),
	adLib                   = require('adal-node'),
	common                  = require('azure-common'),
	NetworkManagementClient = require('azure-arm-network');

async.waterfall([
	(done) => {
		done(null, adLib.createAuthenticationContext('https://login.microsoftonline.com/' + TENANT));
	},
	(context, done) => {
		context.acquireTokenWithClientCredentials(RESOURCE, CLIENT_ID, CLIENT_SECRET, done);
	},
	(tokenResponse, done) => {
		var credentials = new common.TokenCloudCredentials({
			subscriptionId: SUBSCRIPTION,
			token: tokenResponse.accessToken
		});

		var networkMngmtClient = new NetworkManagementClient(credentials, SUBSCRIPTION);

		done(null, networkMngmtClient);
	},
	(networkMngmtClient, done) => {
		networkMngmtClient.publicIPAddresses.createOrUpdate(RESOURCE_GROUP, 'mypublicip', {
			location: 'West US',
			publicIPAllocationMethod: 'Dynamic',
			dnsSettings: {
				domainNameLabel: 'mypublicip'
			},
			idleTimeoutInMinutes: 4
		}, done);
	}
], function (error, result) {
	if (error) console.error(error);

	console.log('Result', result);
});
```

Need help urgently.

**Comment by amarzavery** [comment]
@benjsicam - What version of azure-arm-network are you using?
If you look at this sample script: https://github.com/Azure/azure-sdk-for-node/blob/master/examples/ARM/compute/vm-sample.js, it will provide you information about creating credentials, the runtime package (ms-rest-azure) and how things are used together.

In the sample, a vnet, NIC, publicIP, etc. are being created. The sample should solve most of your problems.

**Comment by benjsicam** [comment]
Wow! That one worked flawless!

**Comment by amarzavery** [comment]
Welcome :).

**Comment by benjsicam** [comment]
Anyway, if in case anyone might be able to see this thread and also using Azure ARM DNS and Azure ARM Traffic Manager, here is how you provide credentials to your ARM Clients:

```javascript
var async                   = require('async'),
	msRestAzure             = require('ms-rest-azure'),
	DnsManagementClient     = require('azure-arm-dns');

async.waterfall([
	(done) => {
		let credentials = new msRestAzure.ApplicationTokenCredentials(CLIENT_ID, 'contoso.com', CLIENT_SECRET);

		credentials.subscriptionId = SUBSCRIPTION; // Add the Subscription ID here
		let dnsMngmtClient = DnsManagementClient.createDnsManagementClient(credentials); // This method does not accept a Subscription ID unlike creating clients for Compute, Network etc.

		done(null, dnsMngmtClient);
	},
	(dnsMngmtClient, done) => {
		dnsMngmtClient.recordSets.createOrUpdate(RESOURCE_GROUP, 'contoso.com', 'blog', 'CNAME', {
			recordSet: {
				location: 'global',
				name: 'blog',
				type: 'Microsoft.Network/dnszones/CNAME',
				properties: {
					ttl: 3600,
					cnameRecord: {
						cname: 'contoso.mycms.com'
					}
				}
			}
		}, done);
	}
], function (error, result) {
	if (error) console.error(error);

	console.log('Result', result);
});
```
