### ISSUE TITLE
Error in deployment connect EACCES

### ISSUE THREAD

**Issue by mauricionr** [Azure/azure-sdk-for-node#1740]
Hey, I'm trying to deploy my API to azure web app and i'm getting this error

```log
remote: Selected node.js version 5.6.0. Use package.json file to choose a different version.
remote: Selected npm version 3.6.0
remote: Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
remote: ...............................................................................................
remote: npm ERR! fetch failed https://registry.npmjs.org/bytes/-/bytes-2.2.0.tgz
remote: npm WARN retry will retry, error on last attempt: Error: connect EACCES 23.235.40.162:443 - Local (undefined:undefined)
remote: npm ERR! fetch failed https://registry.npmjs.org/accepts/-/accepts-1.3.3.tgz
remote: npm WARN retry will retry, error on last attempt: Error: connect EACCES 23.235.40.162:443 - Local (undefined:undefined)
remote: ...............
remote: npm ERR! Windows_NT 6.2.9200
remote: npm ERR! argv "D:\\Program Files (x86)\\nodejs\\5.6.0\\node.exe" "D:\\Program Files (x86)\\npm\\3.6.0\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! node v5.6.0
remote: npm ERR! npm  v3.6.0
remote: npm ERR! code EACCES
remote: npm ERR! errno EACCES
remote: npm ERR! syscall connect
remote:
remote: npm ERR! Error: connect EACCES 23.235.40.162:443 - Local (undefined:undefined)
remote: npm ERR!     at Object.exports._errnoException (util.js:856:11)
remote: npm ERR!     at exports._exceptionWithHostPort (util.js:879:20)
remote: npm ERR!     at connect (net.js:843:16)
remote: npm ERR!     at net.js:976:7
remote: npm ERR!     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
remote: npm ERR!     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
remote: npm ERR!  { [Error: connect EACCES 23.235.40.162:443 - Local (undefined:undefined)]
remote: npm ERR!   code: 'EACCES',
remote: npm ERR!   errno: 'EACCES',
remote: npm ERR!   syscall: 'connect',
remote: npm ERR!   address: '23.235.40.162',
remote: npm ERR!   port: 443,
remote: npm ERR!   parent: 'compression' }
remote: npm ERR!
remote: npm ERR! Please try running this command again as root/Administrator.
remote:
remote: npm ERR! Please include the following file with any support request:
remote: npm ERR!     D:\home\site\wwwroot\npm-debug.log
remote: Failed exitCode=1, command="D:\Program Files (x86)\nodejs\5.6.0\node.exe" "D:\Program Files (x86)\npm\3.6.0\node_modules\npm\bin\npm-cli.js" install --production
remote: An error has occurred during web site deployment.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://{usuario}@{webapp}.scm.azurewebsites.net:443/{git}.git
* [new branch]      api -> api
```

Any ideia?

Thanks in advance!

**Comment by amarzavery** [comment]
@mauricionr - What command/script did you use to deploy the webapp? If you can provide that it would be more helpful.

From the error logs, it looks like there was no network access. Are you behind a proxy?

**Comment by mauricionr** [comment]
I'm just pushing my code to the local repository on azure and i'm not behind a proxy, i'm trying to deploy from home now and i'm getting the same error.

```log
remote: Copying file: 'src\index.html'
remote: Using start-up script index.js from package.json.
remote: Generated web.config.
remote: Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.1
2.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0.
remote: Selected node.js version 5.6.0. Use package.json file to choose a different version.
remote: Selected npm version 3.6.0
remote: Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
remote: ...................................................................................................
remote: npm ERR! fetch failed https://registry.npmjs.org/bytes/-/bytes-2.2.0.tgz
remote: npm WARN retry will retry, error on last attempt: Error: connect EACCES 199.27.79.162:443 - Local (undefined:undefined)
remote: ...........................................................................
remote: npm ERR! fetch failed https://registry.npmjs.org/bytes/-/bytes-2.2.0.tgz
remote: npm WARN retry will retry, error on last attempt: Error: connect EACCES 23.235.40.162:443 - Local (undefined:undefined)
remote: ......................................................................................................................
remote: Command 'starter.cmd "D:\home\site\d ...' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this
remote: Job) if needed.
remote: starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://{user}@{webapp}.scm.azurewebsites.net:443/{git}.git
 * [new branch]      api -> api
```

Thanks.

**Comment by mauricionr** [comment]
I deleted the node_modules and run `npm install` again, and every thing ok,

when a push the code to the local repository on azure i've got the same error but with a diferent package on npm

```log
remote: Copying file: 'src\index.html'
remote: Using start-up script index.js from package.json.
remote: Generated web.config.
remote: Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.1
2.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0.
remote: Selected node.js version 5.6.0. Use package.json file to choose a different version.
remote: Selected npm version 3.6.0
remote: Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
remote: .........................................................................................................
remote: npm ERR! fetch failed https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz
remote: npm WARN retry will retry, error on last attempt: Error: connect EACCES 199.27.76.162:443 - Local (undefined:undefined)
remote: ..........................................................................
remote: npm ERR! fetch failed https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz
remote: npm WARN retry will retry, error on last attempt: Error: connect EACCES 23.235.46.162:443 - Local (undefined:undefined)
remote: ...................................................................................................................
remote: Command 'starter.cmd "D:\home\site\d ...' was aborted due to no output nor CPU activity for 61 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this
remote: Job) if needed.
remote: starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://{user}@{webapp}.scm.azurewebsites.net:443/{git}.git
 * [new branch]      api -> api
```

**Comment by mauricionr** [comment]
```log
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id 'b83fb98478'.
remote: Generating deployment script.
remote: Running deployment command...
remote: Handling node.js deployment.
remote: KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
remote: Using start-up script index.js from package.json.
remote: Generated web.config.
remote: Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.1
2.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0.
remote: Selected node.js version 5.6.0. Use package.json file to choose a different version.
remote: Selected npm version 3.6.0
remote: Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
remote: ...............................................................................
remote: npm ERR! fetch failed https://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz
remote: npm WARN retry will retry, error on last attempt: Error: connect EACCES 23.235.39.162:443 - Local (undefined:undefined)
remote: ..........................................................................
remote: npm ERR! fetch failed https://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz
remote: npm WARN retry will retry, error on last attempt: Error: connect EACCES 23.235.39.162:443 - Local (undefined:undefined)
remote: ...................................................................................................................
remote: Command 'starter.cmd "D:\home\site\d ...' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this
remote: Job) if needed.
remote: starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://{user}@{webapp}.scm.azurewebsites.net:443/{git}.git
 * [new branch]      master -> master
```

**Comment by eduardkoller** [comment]
Looping in @davidebbo for Azure web apps.
@mauricionr, can you please provide the command line that you used to deploy?

**Comment by davidebbo** [comment]
See https://github.com/felixrieseberg/Ghost-Azure/issues/30. In short, it's something we need to solve, but the workaround is to use Basic/Standard.

**Comment by mauricionr** [comment]
It's a nodejs aplication, i'm deploying with git, `git push azure master`, and in my package.json i have a few dependencies, after a lot attempts i finally got my app deployed but with errors on npm install.

I will change to Basic/Standard, thanks @davidebbo @eduardkoller 

Thanks again!

**Comment by davidebbo** [comment]
@mauricionr yes, the issue I point to is Node specific. Basic/Standard will definitely fix it.

**Comment by amarzavery** [comment]
@mauricionr - Does this solve your issue?

**Comment by mauricionr** [comment]
Yes, solved!

Thanks!!
