### ISSUE TITLE
Queue deleted and re-created behaves unpredictably

### ISSUE THREAD

**Issue by michalc-mit** [Azure/azure-sdk-for-node#1831]
After deleting queue with deleteQueue and creating again (createQueue), operations on that queue (e.g. sendQueueMessage, receiveQueueMessage), randomly return 404 error.

``` node
var azure = require('azure-sb')

var connStr = process.env.CONNECTION_STRING;
if (!connStr)
  throw new Error('Must provide connection string (CONNECTION_STRING)');
var queueName = 'sbqtest';

console.log('Connecting to ' + connStr + ' queue ' + queueName);
var sbService = azure.createServiceBusService(connStr);

sbService.createQueueIfNotExists(queueName, function (err) {

  if (err) {
   console.log('Failed to create queue: ', err);
   return;
  }

  console.log('Queue created successfully!')

  sbService.deleteQueue(queueName, function(err) {

    if(err){
      console.log('Failed to delete queue: ', err);
      return;
    }

    console.log('Queue deleted successfully!')

    sbService.createQueue(queueName, function (err) {
      if (err) {
       console.log('Failed to create queue again: ', err);
       return;
      }

      console.log('Queue created again successfully!')

      sbService.sendQueueMessage(queueName, "Hello world!", function (err) {
        if (err) {
          console.log('Failed Tx: ', err);
        } else {
         console.log('Msg sent successfully!');
        }
      });
    });   
  });
});
```

Sometimes output is as expected:

```
Queue created successfully!
Queue deleted successfully!
Queue created again successfully!
Msg sent successfully!
```

But sometimes 404 error appears:

```
Queue created successfully!
Queue deleted successfully!
Queue created again successfully!
Failed Tx:  { Error: NotFound
    at Function.ServiceClient._normalizeError (/home/xxx/workspace/servicebus-bug/node_modules/azure-common/lib/services/serviceclient.js:814:23)
    at ServiceBusService.ServiceClient._processResponse (/home/xxx/workspace/servicebus-bug/node_modules/azure-common/lib/services/serviceclient.js:455:41)
    at Request.processResponseCallback [as _callback] (/home/xxx/workspace/servicebus-bug/node_modules/azure-common/lib/services/serviceclient.js:213:35)
    at Request.self.callback (/home/xxx/workspace/servicebus-bug/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/xxx/workspace/servicebus-bug/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/xxx/workspace/servicebus-bug/node_modules/request/request.js:988:12) code: 'NotFound', statusCode: 404 }
```

Probably it's worth to mention that this error is different than an error issued when the queue really doesn't exist.
I'm not sure if it's a problem of azure-sdk-for-node or (what is more likely) servicebus rest api.

**Comment by amarzavery** [comment]
@sazeesha - Can you take a look at this issue?

**Comment by jtaubensee** [comment]
@michalc-mit - Is this still an issue? Please re-open if it is.
