### ISSUE TITLE
Missing dependency - moment

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-sdk-for-node#1854]
The package version 1.1.1-preview is missing a dependency. Steps to reproduce:

npm install azure
node
require('azure')

results in:

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\azure\node_modules\azure\node_modules\azure-batch\lib\models\usageStatistics.js:13:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by jeffwilcox** [comment]
@maggiepint figured you would enjoy this!

**Comment by amarzavery** [comment]
This should be fixed with the new 1.2.0-preview version of azure
