### ISSUE TITLE
Azure invalid content length errors being reported as content-type error

### ISSUE THREAD

**Issue by geuis** [Azure/azure-sdk-for-node#1908]
Kind of ran into this sideways.

I was accidentally setting an invalid content length value as a string that couldn't be parsed to a number. The error from the sdk is:

```
{"msec":204.5356139987707,"error":"StorageError: Content-Type response header is missing or invalid.","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":400,"payload":{"statusCode":400,"error":"Bad Request","message":"StorageError: Content-Type response header is missing or invalid."},"headers":{}}}}
```

However, the error being returned from Azure is:

```
{ isSuccessful: false,
statusCode: 400,
body: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>\r\n<BODY><h2>Bad Request - Invalid Content Length</h2>\r\n<hr><p>HTTP Error 400. There is an invalid content length or chunk length in the request.</p>\r\n</BODY></HTML>\r\n',
headers: 
 { 'content-type': 'text/html; charset=us-ascii',
   server: 'Microsoft-HTTPAPI/2.0',
   date: 'Wed, 28 Sep 2016 01:44:48 GMT',
   connection: 'close',
   'content-length': '374' },
md5: undefined }
```

This is the stack trace that was reported:

```
StorageError: Content-Type response header is missing or invalid.
  at Function.StorageServiceClient._normalizeError (/usr/local/apps/makersteps/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1146:23)
  at BlobService.StorageServiceClient._processResponse (/usr/local/apps/makersteps/node_modules/azure-storage/lib/common/services/storageserviceclient.js:706:50)
  at Request.processResponseCallback [as _callback] (/usr/local/apps/makersteps/node_modules/azure-storage/lib/common/services/storageserviceclient.js:306:37)
  at Request.self.callback (/usr/local/apps/makersteps/node_modules/request/request.js:187:22)
  at emitTwo (events.js:106:13)
  at Request.emit (events.js:191:7)
  at Request.<anonymous> (/usr/local/apps/makersteps/node_modules/request/request.js:1044:10)
  at emitOne (events.js:96:13)
  at Request.emit (events.js:188:7)
  at IncomingMessage.<anonymous> (/usr/local/apps/makersteps/node_modules/request/request.js:965:12)

```

Using azure-storage 1.3.0 and hapi 15.0.1.

**Comment by amarzavery** [comment]
Thanks for reporting this issue. However, this rightly belongs to the azure-storage-node repo over [here](https://github.com/Azure/azure-storage-node).

@geuis - I have filed an issue for you in the storage-node repo and it is https://github.com/Azure/azure-storage-node/issues/202
