### ISSUE TITLE
Error Windows_NT 6.2.9200 on azure on execution of postinstall command

### ISSUE THREAD

**Issue by VishalGulati** [Azure/azure-sdk-for-node#1946]
I am getting below log on Azure deployment of my Angular2 application.

```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0.
Selected node.js version 6.1.0. Use package.json file to choose a different version.
Selected npm version 3.8.6
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
angular-quickstart@1.0.0 D:\home\site\wwwroot
+-- firebase@3.5.2 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
| +-- dom-storage@2.0.2 
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
| +-- faye-websocket@0.9.3 
npm WARN angularfire2@2.0.0-beta.5 requires a peer of @types/request@0.0.30 but none was installed.
| | `-- websocket-driver@0.6.4 
npm WARN angular-quickstart@1.0.0 No license field.
| |   `-- websocket-extensions@0.1.1 
npm ERR! Windows_NT 6.2.9200
| +-- jsonwebtoken@5.7.0 
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\6.1.0\\node.exe" "D:\\Program Files (x86)\\npm\\3.8.6\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
| | +-- jws@3.1.3 
npm ERR! node v6.1.0
| | | +-- base64url@1.0.6 
npm ERR! npm  v3.8.6
| | | | +-- concat-stream@1.4.10 
npm ERR! path D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite
npm ERR! code EPERM
| | | | | +-- inherits@2.0.1 
npm ERR! errno -4048
| | | | | +-- readable-stream@1.1.14 
npm ERR! syscall rename
| | | | | | +-- core-util-is@1.0.2 

| | | | | | +-- isarray@0.0.1 
npm ERR! Error: EPERM: operation not permitted, rename 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite' -> 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\.is-finite.DELETE'
| | | | | | `-- string_decoder@0.10.31 
npm ERR!     at moveAway (D:\Program Files (x86)\npm\3.8.6\node_modules\npm\lib\install\action\finalize.js:38:5)
| | | | | `-- typedarray@0.0.6 
npm ERR!     at destStatted (D:\Program Files (x86)\npm\3.8.6\node_modules\npm\lib\install\action\finalize.js:27:7)
| | | | `-- meow@2.0.0 
npm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)
| | | |   +-- camelcase-keys@1.0.0 
npm ERR! 
| | | |   | +-- camelcase@1.2.1 
npm ERR! Error: EPERM: operation not permitted, rename 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite' -> 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\.is-finite.DELETE'
| | | |   | `-- map-obj@1.0.1 
npm ERR!     at Error (native)
| | | |   +-- indent-string@1.2.2 
npm ERR!  { Error: EPERM: operation not permitted, rename 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite' -> 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\.is-finite.DELETE'
| | | |   | +-- get-stdin@4.0.1 
npm ERR!     at moveAway (D:\Program Files (x86)\npm\3.8.6\node_modules\npm\lib\install\action\finalize.js:38:5)
| | | |   | `-- repeating@1.1.3 
| | | |   |   `-- is-finite@1.0.1 
npm ERR!     at destStatted (D:\Program Files (x86)\npm\3.8.6\node_modules\npm\lib\install\action\finalize.js:27:7)
| | | |   |     `-- number-is-nan@1.0.0 
npm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)
| | | |   +-- minimist@1.2.0 
npm ERR! 
| | | |   `-- object-assign@1.0.0 
npm ERR! Error: EPERM: operation not permitted, rename 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite' -> 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\.is-finite.DELETE'
| | | `-- jwa@1.1.3 
npm ERR!     at Error (native) parent: 'repeating' }
| | |   +-- buffer-equal-constant-time@1.0.1 
npm ERR! 
| | |   `-- ecdsa-sig-formatter@1.0.5 
npm ERR! Please try running this command again as root/Administrator.
| | |     `-- base64-url@1.2.2 

| | +-- ms@0.7.1 
npm ERR! Please include the following file with any support request:
| | `-- xtend@4.0.1 
npm ERR!     D:\home\site\wwwroot\npm-debug.log
| +-- rsvp@3.2.1 
| `-- xmlhttprequest@1.8.0  
`-- ng2-bootstrap@1.1.14 
  `-- moment@2.15.1 

Failed exitCode=-4048, command="D:\Program Files (x86)\nodejs\6.1.0\node.exe" "D:\Program Files (x86)\npm\3.8.6\node_modules\npm\bin\npm-cli.js" install --production
An error has occurred during web site deployment.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:\r\nnpm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14\r\nnpm WARN angularfire2@2.0.0-beta.5 requires a peer of @types/request@0.0.30 but none was installed.\r\nnpm WARN angular-quickstart@1.0.0 No license field.\r\nnpm ERR! Windows_NT 6.2.9200\r\nnpm ERR! argv "D:\\Program Files (x86)\\nodejs\\6.1.0\\node.exe" "D:\\Program Files (x86)\\npm\\3.8.6\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"\r\nnpm ERR! node v6.1.0\r\nnpm ERR! npm  v3.8.6\r\nnpm ERR! path D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite\r\nnpm ERR! code EPERM\r\nnpm ERR! errno -4048\r\nnpm ERR! syscall rename\r\n\r\nnpm ERR! Error: EPERM: operation not permitted, rename 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite' -> 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\.is-finite.DELETE'\r\nnpm ERR!     at moveAway (D:\Program Files (x86)\npm\3.8.6\node_modules\npm\lib\install\action\finalize.js:38:5)\r\nnpm ERR!     at destStatted (D:\Program Files (x86)\npm\3.8.6\node_modules\npm\lib\install\action\finalize.js:27:7)\r\nnpm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)\r\nnpm ERR! \r\nnpm ERR! Error: EPERM: operation not permitted, rename 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite' -> 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\.is-finite.DELETE'\r\nnpm ERR!     at Error (native)\r\nnpm ERR!  { Error: EPERM: operation not permitted, rename 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite' -> 'D:\home\site\wwwroot\node_modules\angularfire2\node_modules\firebase\node_modules\jsonwebtoken\node_modules\jws\node_modules\base64url\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\.is-finite.DELETE'\r\nnpm ERR!     at moveAway (D:\Program Files (x86)\npm\3.8.6\node_modules\npm\lib\install\action\finalize.js:38:5)\r\nnpm ERR!     at destStatted (D:\Program Files (x86)\npm\3.8.6\node_modules\npm\lib\install\action\finalize.js:27:7)\r\nnpm ERR!
```

I have executed command "npm cache clean" as suggested by various posts but did not help me. Anyone having any idea about thi pls share. TIA.

For your reference, here is my package.json:

```
{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "engines": {
    "node": "6.1.0",
    "npm": "3.8.6"
  }, 
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "docker-build": "docker build -t ng2-quickstart .",
    "docker": "npm run docker-build && docker run -it --rm -p 3000:3000 -p 3001:3001 ng2-quickstart",
    "pree2e": "npm run webdriver:update",
    "e2e": "tsc && concurrently \"http-server -s\" \"protractor protractor.config.js\" --kill-others --success first",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "node_modules\\.bin\\lite-server",
    "postinstall": "typings install && tsc",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "test-once": "tsc && karma start karma.conf.js --single-run",
    "tsc": "node_modules\\.bin\\tsc",
    "concurrently": "node_modules\\.bin\\concurrently",
    "tsc:w": "node_modules\\.bin\\tsc -w",
    "typings": "node_modules\\.bin\\typings",
    "webdriver:update": "webdriver-manager update"
  },
  "keywords": [],
  "author": "",
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/angular/angular.io/blob/master/LICENSE"
    }
  ],
  "dependencies": {
    "@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
    "@angular/forms": "~2.1.0",
    "@angular/http": "~2.1.0",
    "@angular/platform-browser": "~2.1.0",
    "@angular/platform-browser-dynamic": "~2.1.0",
    "@angular/router": "~3.1.0",
    "@angular/upgrade": "~2.1.0",

    "angular-in-memory-web-api": "~0.1.5",
    "bootstrap": "^3.3.7",
    "ng2-bootstrap": "^1.1.14",
    "moment": "^2.15.2",
    "firebase": "^3.5.2",
    "angularfire2": "^2.0.0-beta.5",
    "systemjs": "0.19.39",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.25",
    "concurrently": "^3.0.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.3",
    "typings": "^1.4.0"
  },
  "devDependencies": {
    "concurrently": "^3.0.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.3",
    "typings": "^1.4.0",

    "canonical-path": "0.0.2",
    "http-server": "^0.9.0",
    "tslint": "^3.15.1",
    "lodash": "^4.16.2",
    "jasmine-core": "~2.5.2",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-htmlfile-reporter": "^0.3.4",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^3.3.0",
    "rimraf": "^2.5.4"
  },
  "repository": {}
}

```

**Comment by amarzavery** [comment]
This has got nothing to do with the node sdk. It looks like a webapp deployment issue.
