### ISSUE TITLE
azure-arm-sql cannot be used in Vsts custom build agent

### ISSUE THREAD

**Issue by LoulG** [Azure/azure-sdk-for-node#2128]
When debugging a custom Vsts task that uses azure-arm-sql from local machine, the task runs well. Once uploaded to Vsts custom build agent, the task fails with `Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`. I compile (ES6) using the `--alwaysStrict` flag.

NodeJs version: 7.8.0 on both local machine and build agent (2.115.0)

More info:

> F:\Agent1\_work\_tasks\DatabaseCreator_bebda000-1c4c-11e7-a748-8fdbf6e36141\0.0.11\node_modules\ms-rest\lib\utils.js:51 
> 2017-04-09T08:41:13.4016185Z   let strippedResponse = {}; 
> 2017-04-09T08:41:13.4016185Z   ^^^ 
> 2017-04-09T08:41:13.4016185Z  
> 2017-04-09T08:41:13.4016185Z SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode 
> 2017-04-09T08:41:13.4016185Z     at exports.runInThisContext (vm.js:53:16) 
> 2017-04-09T08:41:13.4016185Z     at Module._compile (module.js:387:25) 
> 2017-04-09T08:41:13.4016185Z     at Object.Module._extensions..js (module.js:422:10) 
> 2017-04-09T08:41:13.4016185Z     at Module.load (module.js:357:32) 
> 2017-04-09T08:41:13.4016185Z     at Function.Module._load (module.js:314:12) 
> 2017-04-09T08:41:13.4016185Z     at Module.require (module.js:367:17) 
> 2017-04-09T08:41:13.4016185Z     at require (internal/module.js:16:19) 
> 2017-04-09T08:41:13.4016185Z     at Object.<anonymous> (F:\Agent1\_work\_tasks\DatabaseCreator_bebda000-1c4c-11e7-a748-8fdbf6e36141\0.0.11\node_modules\ms-rest\lib\msRest.js:4:15) 
> 2017-04-09T08:41:13.4016185Z     at Module._compile (module.js:413:34) 
> 2017-04-09T08:41:13.4016185Z     at Object.Module._extensions..js (module.js:422:10)

**Comment by LoulG** [comment]
moved to another more precise issue: https://github.com/Azure/azure-sdk-for-node/issues/2129
