### ISSUE TITLE
sendTopicMessage not accepting object as a paramater

### ISSUE THREAD

**Issue by ZebpayHitesh** [Azure/azure-sdk-for-node#2181]
I have been trying to call sendTopicMessage like below, but the second parameter is not getting accepted until unless I stringify it and send it.
If i stringify it I am unable to set the brokerProperties.Label.
````
sbService.sendTopicMessage('BusinessEvent',{"body" : {DB_id : parseInt(TxID,10)},"brokerProperties" : {Label : "testing"}}, function (err,receivetopicmessageresult,response) {
   if (err) {
     console.log('Failed Tx: ', err);
     callback(err); 
    }
   
     console.log('Sent ' + JSON.stringify(receivetopicmessageresult));
     callback(err,receivetopicmessageresult);
  });
````
The error I am getting is: 
````
Error: 
_http_outgoing.js:456
    throw new TypeError('First argument must be a string or Buffer');
    ^

TypeError: First argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:456:11)
    at Request.write (/var/www/html/Myoperator/support-scripts/BusEventRaiser/node_modules/request/request.js:1514:27)
    at end (/var/www/html/Myoperator/support-scripts/BusEventRaiser/node_modules/request/request.js:552:18)
    at Immediate.<anonymous> (/var/www/html/Myoperator/support-scripts/BusEventRaiser/node_modules/request/request.js:581:7)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
````

**Comment by ZebpayHitesh** [comment]
Ok Guys I got a work around while fiddeling :+1: 
` let msg= {
    body :JSON.stringify({DB_id : parseInt(TxID,10)}),
    brokerProperties: {Label : 'testing'},
    customProperties: {messagenumber: 1,
                       Category : 4}
  };`

The first paramater of your msg object must be `string` as in this case body(key) has `stringified value`
