### ISSUE TITLE
[keyvault] - throws Error: Property  has invalid value after 2KB

### ISSUE THREAD

**Issue by oreporan** [Azure/azure-sdk-for-node#2198]
I'm trying to set a secret using the library. When the secret value is under 2kb it works, but when the string is 2KB it fails on `Error: Property  has invalid value`
According to the docs the max size is 25KB
Note - the string is a JSON parsed into a string, but this didn't cause any issues under 2kb

Stacktrace:

```
[20:14:32][docker] Error: Error setting secret SomeSecret in keyvault, with value{"......."} //2kb size file 
[20:14:32][docker] Error: Property  has invalid value
[20:14:32][docker] 
[20:14:32][docker]     at /checkout/internal/index.js:111:23
[20:14:32][docker]     at client.pipeline.error (/checkout/node_modules/azure-keyvault/lib/keyVaultClient.js:2924:14)
[20:14:32][docker]     at retryCallback (/checkout/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:89:9)
[20:14:32][docker]     at retryCallback (/checkout/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
[20:14:32][docker]     at handleRedirect (/checkout/node_modules/ms-rest/lib/filters/redirectFilter.js:39:9)
[20:14:32][docker]     at Request.defaultRequest [as _callback] (/checkout/node_modules/ms-rest/lib/requestPipeline.js:125:16)
[20:14:32][docker]     at Request.self.callback (/checkout/node_modules/request/request.js:188:22)
[20:14:32][docker]     at emitTwo (events.js:106:13)
[20:14:32][docker]     at Request.emit (events.js:191:7)
[20:14:32][docker]     at Request.<anonymous> (/checkout/node_modules/request/request.js:1171:10)
```

**Comment by oreporan** [comment]
Turns out the Tags have a max char limit
