### ISSUE TITLE
Cannot serialize NSG security rules

### ISSUE THREAD

**Issue by taiyokato** [Azure/azure-sdk-for-node#2265]
Hi all,

I'm trying to create a new NSG using NetworkManagementClient.networkSecurityGroups.createOrUpdate.

My params object is the following:
```javascript
let nsgparams = {
		location: default_location,
		defaultSecurityRules: [
		{
			"name": "AllowVnetInBound",
			"properties": {
				"description": "Allow inbound traffic from all VMs in VNET",
				"protocol": "*",
				"sourcePortRange": "*",
				"destinationPortRange": "*",
				"sourceAddressPrefix": "VirtualNetwork",
				"destinationAddressPrefix": "VirtualNetwork",
				"access": "Allow",
				"priority": 65000,
				"direction": "Inbound",
				"sourceAddressPrefixes": "VirtualNetwork",
				"destinationAddressPrefixes": "VirtualNetwork"
			}
		},
		{
			"name": "AllowAzureLoadBalancerInBound",
			"properties": {
				"description": "Allow inbound traffic from azure load balancer",
				"protocol": "*",
				"sourcePortRange": "*",
				"destinationPortRange": "*",
				"sourceAddressPrefix": "AzureLoadBalancer",
				"destinationAddressPrefix": "*",
				"access": "Allow",
				"priority": 65001,
				"direction": "Inbound",
				"sourceAddressPrefixes": "AzureLoadBalancer",
				"destinationAddressPrefixes": "*"
			}
		},
		{
			"name": "DenyAllInBound",
			"properties": {
				"description": "Deny all inbound traffic",
				"protocol": "*",
				"sourcePortRange": "*",
				"destinationPortRange": "*",
				"sourceAddressPrefix": "*",
				"destinationAddressPrefix": "*",
				"access": "Deny",
				"priority": 65500,
				"direction": "Inbound",
				"sourceAddressPrefixes": "*",
				"destinationAddressPrefixes": "*"
			}
		},
		{
			"name": "AllowVnetOutBound",
			"properties": {
				"description": "Allow outbound traffic from all VMs to all VMs in VNET",
				"protocol": "*",
				"sourcePortRange": "*",
				"destinationPortRange": "*",
				"sourceAddressPrefix": "VirtualNetwork",
				"destinationAddressPrefix": "VirtualNetwork",
				"access": "Allow",
				"priority": 65000,
				"direction": "Outbound",
				"sourceAddressPrefixes": "VirtualNetwork",
				"destinationAddressPrefixes": "VirtualNetwork"
			}
		},
		{
			"name": "AllowInternetOutBound",
			"properties": {
				"description": "Allow outbound traffic from all VMs to Internet",
				"protocol": "*",
				"sourcePortRange": "*",
				"destinationPortRange": "*",
				"sourceAddressPrefix": "*",
				"destinationAddressPrefix": "Internet",
				"access": "Allow",
				"priority": 65001,
				"direction": "Outbound",
				"sourceAddressPrefixes": "*",
				"destinationAddressPrefixes": "Internet"
			}
		},
		{
			"name": "DenyAllOutBound",
			"properties": {
				"description": "Deny all outbound traffic",
				"protocol": "*",
				"sourcePortRange": "*",
				"destinationPortRange": "*",
				"sourceAddressPrefix": "*",
				"destinationAddressPrefix": "*",
				"access": "Deny",
				"priority": 65500,
				"direction": "Outbound",
				"sourceAddressPrefixes": "*",
				"destinationAddressPrefixes": "*"
			}
		}],
		securityRules: [
		{
			"name": "default-allow-ssh",
			"properties": {
				"protocol": "Tcp",
				"sourcePortRange": "*",
				"destinationPortRange": "22",
				"sourceAddressPrefix": "*",
				"destinationAddressPrefix": "*",
				"access": "Allow",
				"priority": 1000,
				"direction": "Inbound",
				"sourceAddressPrefixes": "*",
				"destinationAddressPrefixes": "*"
			}
		},
		{
			"name": "SMB_Port_445",
			"properties": {
				"protocol": "Tcp",
				"sourcePortRange": "*",
				"destinationPortRange": "445",
				"sourceAddressPrefix": "*",
				"destinationAddressPrefix": "*",
				"access": "Allow",
				"priority": 1010,
				"direction": "Inbound",
				"sourceAddressPrefixes": "*",
				"destinationAddressPrefixes": "*"
			}
		},
		{
			"name": "HTTPS",
			"properties": {
				"protocol": "Tcp",
				"sourcePortRange": "*",
				"destinationPortRange": "443",
				"sourceAddressPrefix": "*",
				"destinationAddressPrefix": "*",
				"access": "Allow",
				"priority": 100,
				"direction": "Inbound",
				"sourceAddressPrefixes": "*",
				"destinationAddressPrefixes": "*"
			}
		},
		{
			"name": "HTTP",
			"properties": {
				"protocol": "Tcp",
				"sourcePortRange": "*",
				"destinationPortRange": "80",
				"sourceAddressPrefix": "*",
				"destinationAddressPrefix": "*",
				"access": "Allow",
				"priority": 101,
				"direction": "Inbound",
				"sourceAddressPrefixes": "*",
				"destinationAddressPrefixes": "*"
			}
		}]
	}
```

and the createOrUpdate() line:

```
return networkClient.networkSecurityGroups.createOrUpdate(rgname, nsgname, nsgparams, null, callback);
```

The params object looks fine, parses fine with JSON RFC 4627 (using JSON formatter), and Chrome console.

However on run, the serializer seems to not like what its given and throws a 

```
Failed with error:  Error: Error "protocol" cannot be null or undefined in "parameters.properties.securityRules"." occurred in serializing the payload - 
(...params object above...)
 at NetworkSecurityGroups._beginCreateOrUpdate (/home/taiyo/[PROJECT NAME]/node_modules/azure-arm-network/lib/operations/networkSecurityGroups.js:859:30)
    at NetworkSecurityGroups.beginCreateOrUpdate (/home/taiyo/[PROJECT NAME]/node_modules/azure-arm-network/lib/operations/networkSecurityGroups.js:1917:19)
    at NetworkSecurityGroups._createOrUpdate (/home/taiyo/[PROJECT NAME]/node_modules/azure-arm-network/lib/operations/networkSecurityGroups.js:299:8)
    at NetworkSecurityGroups.createOrUpdate (/home/taiyo/[PROJECT NAME]/node_modules/azure-arm-network/lib/operations/networkSecurityGroups.js:1530:19)
    at Object.createNSG (/home/taiyo/[PROJECT NAME]/azure.js:399:45)
    at /home/taiyo/[PROJECT NAME]/test.js:30:7
    at client.getLongRunningOperationResult.error (/home/taiyo/[PROJECT NAME]/node_modules/azure-arm-network/lib/operations/publicIPAddresses.js:356:14)
    at self._updateStateFromGetResourceOperation (/home/taiyo/[PROJECT NAME]/node_modules/ms-rest-azure/lib/azureServiceClient.js:151:20)
    at /home/taiyo/[PROJECT NAME]/node_modules/ms-rest-azure/lib/azureServiceClient.js:252:5
    at /home/taiyo/[PROJECT NAME]/node_modules/ms-rest-azure/lib/azureServiceClient.js:322:12
```

All values for 'protocol' are string so it should be fine.

Any ideas?

Thanks in advance.

**Comment by amarzavery** [comment]
To make it easier for our customers we have flattened the properties under "properties" property. While serialization we will move it inside "properties" for you. Thus you do not have to nest things inside properties all the time.

```javascript
let nsgparams = {
  "location": default_location,
  "defaultSecurityRules": [
    {
      "name": "AllowVnetInBound",
      "description": "Allow inbound traffic from all VMs in VNET",
      "protocol": "*",
      "sourcePortRange": "*",
      "destinationPortRange": "*",
      "sourceAddressPrefix": "VirtualNetwork",
      "destinationAddressPrefix": "VirtualNetwork",
      "access": "Allow",
      "priority": 65000,
      "direction": "Inbound",
      "sourceAddressPrefixes": "VirtualNetwork",
      "destinationAddressPrefixes": "VirtualNetwork"
    },
    {
      "name": "AllowAzureLoadBalancerInBound",
      "description": "Allow inbound traffic from azure load balancer",
      "protocol": "*",
      "sourcePortRange": "*",
      "destinationPortRange": "*",
      "sourceAddressPrefix": "AzureLoadBalancer",
      "destinationAddressPrefix": "*",
      "access": "Allow",
      "priority": 65001,
      "direction": "Inbound",
      "sourceAddressPrefixes": "AzureLoadBalancer",
      "destinationAddressPrefixes": "*"
    },
    {
      "name": "DenyAllInBound",
      "description": "Deny all inbound traffic",
      "protocol": "*",
      "sourcePortRange": "*",
      "destinationPortRange": "*",
      "sourceAddressPrefix": "*",
      "destinationAddressPrefix": "*",
      "access": "Deny",
      "priority": 65500,
      "direction": "Inbound",
      "sourceAddressPrefixes": "*",
      "destinationAddressPrefixes": "*"
    },
    {
      "name": "AllowVnetOutBound",
      "description": "Allow outbound traffic from all VMs to all VMs in VNET",
      "protocol": "*",
      "sourcePortRange": "*",
      "destinationPortRange": "*",
      "sourceAddressPrefix": "VirtualNetwork",
      "destinationAddressPrefix": "VirtualNetwork",
      "access": "Allow",
      "priority": 65000,
      "direction": "Outbound",
      "sourceAddressPrefixes": "VirtualNetwork",
      "destinationAddressPrefixes": "VirtualNetwork"
    },
    {
      "name": "AllowInternetOutBound",
      "description": "Allow outbound traffic from all VMs to Internet",
      "protocol": "*",
      "sourcePortRange": "*",
      "destinationPortRange": "*",
      "sourceAddressPrefix": "*",
      "destinationAddressPrefix": "Internet",
      "access": "Allow",
      "priority": 65001,
      "direction": "Outbound",
      "sourceAddressPrefixes": "*",
      "destinationAddressPrefixes": "Internet"
    },
    {
      "name": "DenyAllOutBound",
      "description": "Deny all outbound traffic",
      "protocol": "*",
      "sourcePortRange": "*",
      "destinationPortRange": "*",
      "sourceAddressPrefix": "*",
      "destinationAddressPrefix": "*",
      "access": "Deny",
      "priority": 65500,
      "direction": "Outbound",
      "sourceAddressPrefixes": "*",
      "destinationAddressPrefixes": "*"
    }
  ],
  "securityRules": [
    {
      "name": "default-allow-ssh",
      "protocol": "Tcp",
      "sourcePortRange": "*",
      "destinationPortRange": "22",
      "sourceAddressPrefix": "*",
      "destinationAddressPrefix": "*",
      "access": "Allow",
      "priority": 1000,
      "direction": "Inbound",
      "sourceAddressPrefixes": "*",
      "destinationAddressPrefixes": "*"
    },
    {
      "name": "SMB_Port_445",
      "protocol": "Tcp",
      "sourcePortRange": "*",
      "destinationPortRange": "445",
      "sourceAddressPrefix": "*",
      "destinationAddressPrefix": "*",
      "access": "Allow",
      "priority": 1010,
      "direction": "Inbound",
      "sourceAddressPrefixes": "*",
      "destinationAddressPrefixes": "*"
    },
    {
      "name": "HTTPS",
      "protocol": "Tcp",
      "sourcePortRange": "*",
      "destinationPortRange": "443",
      "sourceAddressPrefix": "*",
      "destinationAddressPrefix": "*",
      "access": "Allow",
      "priority": 100,
      "direction": "Inbound",
      "sourceAddressPrefixes": "*",
      "destinationAddressPrefixes": "*"
    },
    {
      "name": "HTTP",
      "protocol": "Tcp",
      "sourcePortRange": "*",
      "destinationPortRange": "80",
      "sourceAddressPrefix": "*",
      "destinationAddressPrefix": "*",
      "access": "Allow",
      "priority": 101,
      "direction": "Inbound",
      "sourceAddressPrefixes": "*",
      "destinationAddressPrefixes": "*"
    }
  ]
};

return networkClient.networkSecurityGroups.createOrUpdate(rgname, nsgname, nsgparams, callback);
```

Try this and let me know.

**Comment by taiyokato** [comment]
@amarzavery

Thank you for the quick response.
I have tested your snippet and it worked!

**Comment by amarzavery** [comment]
cool. try writing your app in typescript. We have type definitions for all the operations and models.
That will give you good intellisense and compile time errors. (I assume you must be using vscode as the ide)
