### ISSUE TITLE
400 Invalid URL: Blob with special UTF-8 character

### ISSUE THREAD

**Issue by bennettbuchanan** [Azure/azure-sdk-for-node#2344]
When using a blob with the character `` (for example, with a blob `'㒈保'`) I receive 400 Invalid URL.

My code:

```js
const azure = require('azure-storage');

[...]

const containerName = 'my-container';
const blob = '㒈保';

sharedBlobSvc.logger = new azure.Logger(azure.Logger.LogLevels.DEBUG);

sharedBlobSvc.createBlockBlobFromText(containerName, blob, undefined,
    (err, result) => {
        if (err) {
            return console.log(err);
        }
        return console.log(result);
});
```

Here is the debug log:

```
[2017-12-06T01:29:42.639Z]debug : FINAL REQUEST OPTIONS:
{ uri: 'https://test.blob.core.windows.net:443/my-container/%E3%92%88%EF%80%83%E4%BF%9D',
  method: 'PUT',
  headers:
   { 'content-type': 'application/octet-stream',
     'x-ms-blob-type': 'BlockBlob',
     'content-length': 0,
     'x-ms-client-request-id': 'ef02fl00-da16-09l3-be6b-3vd1k2b3l2nz',
     'user-agent': 'Azure-Storage/2.6.0 (NODE-VERSION v6.10.0; Darwin 15.6.0)',
     'x-ms-version': '2017-04-17',
     'x-ms-date': 'Wed, 06 Dec 2017 01:29:42 GMT',
     accept: 'application/atom+xml,application/xml',
     'Accept-Charset': 'UTF-8',
     authorization: 'SharedKey test:PnkW+W/1wEqpOswCt/AqIMt4lkPBPgw8eqz01PSDQZo=' },
  mode: 'disable-fetch',
  encoding: undefined,
  timeout: 120000 }
VALID RESPONSE? false
[2017-12-06T01:29:43.120Z]debug : RESPONSE:
{ error:
   { StorageError: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
   <HTML><HEAD><TITLE>Bad Request</TITLE>
   <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
   <BODY><h2>Bad Request - Invalid URL</h2>
   <hr><p>HTTP Error 400. The request URL is invalid.</p>
   </BODY></HTML>

       at Function.StorageServiceClient._normalizeError (/Users/bennettbuchanan/sandbox/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1153:12)
       at BlobService.StorageServiceClient._processResponse (/Users/bennettbuchanan/sandbox/node_modules/azure-storage/lib/common/services/storageserviceclient.js:738:50)
       at Request.processResponseCallback [as _callback] (/Users/bennettbuchanan/sandbox/node_modules/azure-storage/lib/common/services/storageserviceclient.js:311:37)
       at Request.self.callback (/Users/bennettbuchanan/sandbox/node_modules/request/request.js:188:22)
       at emitTwo (events.js:106:13)
       at Request.emit (events.js:191:7)
       at Request.<anonymous> (/Users/bennettbuchanan/sandbox/node_modules/request/request.js:1171:10)
       at emitOne (events.js:96:13)
       at Request.emit (events.js:188:7)
       at IncomingMessage.<anonymous> (/Users/bennettbuchanan/sandbox/node_modules/request/request.js:1091:12)
     name: 'StorageError',
     message: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>\r\n<BODY><h2>Bad Request - Invalid URL</h2>\r\n<hr><p>HTTP Error 400. The request URL is invalid.</p>\r\n</BODY></HTML>\r\n' }
```

**Comment by amarzavery** [comment]
Please open this issue in the https://github.com/azure/azure-storage-node repo.

**Comment by bennettbuchanan** [comment]
Thank you @amarzavery. I've opened it here: https://github.com/Azure/azure-storage-node/issues/385.
