### ISSUE TITLE
TypeError in ServiceClient when handling JSON parse failure

### ISSUE THREAD

**Issue by philliphoff** [Azure/azure-sdk-for-node#2852]
I'm seeing a `TypeError` in the `ServiceClient` when it attempts to handle a JSON parse failure at [serviceClient.js#L63]( https://github.com/Azure/azure-sdk-for-node/blob/f335a833d8386be5a8909b84b3dcdc0ae56a5854/runtime/ms-rest/lib/serviceClient.js#L63).

The error is:

```
Exception has occurred: TypeError
TypeError: Cannot create property 'request' on string '<redacted>'
	at callback.pipeline (/Users/phoff/Source/Personal/vscode-kubernetes-tools/node_modules/ms-rest/lib/serviceClient.js:63:17)
	at retryCallback (/Users/phoff/Source/Personal/vscode-kubernetes-tools/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:89:9)
	at retryCallback (/Users/phoff/Source/Personal/vscode-kubernetes-tools/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
	at /Users/phoff/Source/Personal/vscode-kubernetes-tools/node_modules/ms-rest/lib/filters/rpRegistrationFilter.js:59:14
	at handleRedirect (/Users/phoff/Source/Personal/vscode-kubernetes-tools/node_modules/ms-rest/lib/filters/redirectFilter.js:39:9)
	at /Users/phoff/Source/Personal/vscode-kubernetes-tools/node_modules/ms-rest/lib/filters/formDataFilter.js:23:14
	at Request.exports.requestLibrarySink.defaultRequest [as _callback] (/Users/phoff/Source/Personal/vscode-kubernetes-tools/node_modules/ms-rest/lib/requestPipeline.js:125:16)
	at Request.self.callback (/Users/phoff/Source/Personal/vscode-kubernetes-tools/node_modules/request/request.js:186:22)
	at emitTwo (events.js:106:13)
	at Request.emit (events.js:194:7)
	at Request.<anonymous> (/Users/phoff/Source/Personal/vscode-kubernetes-tools/node_modules/request/request.js:1163:10)
	at emitOne (events.js:101:20)
	at Request.emit (events.js:191:7)
	at IncomingMessage.<anonymous> (/Users/phoff/Source/Personal/vscode-kubernetes-tools/node_modules/request/request.js:1085:12)
	at Object.onceWrapper (events.js:293:19)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

The callback expects an error of type `Error` or `ServiceError` (itself a derivation of `Error`), so it seems odd to be adding a `request` property directly to a string.  Should [L62](https://github.com/Azure/azure-sdk-for-node/blob/f335a833d8386be5a8909b84b3dcdc0ae56a5854/runtime/ms-rest/lib/serviceClient.js#L62) instead have created a new `Error` object?

```
      let e = new Error(`An error occurred while deserializing the responseBody ${responseBody}. The error is:\n ${JSON.stringify(parseError, null, 2)}.`);
```

**Comment by philliphoff** [comment]
I should note that I haven't been able to trap this `TypeError` when using either the callback or `Promise` based calls to `sendRequest()`, which is hampering my use of `ServiceClient` with a REST server that sometimes returns plaintext for errors instead of JSON.

**Comment by RikkiGibson** [comment]
@amarzavery is there anything in Swagger which indicates that the response content on an error is expected to be JSON, or is that an assumption we've made?

**Comment by amarzavery** [comment]
We expect all the errors from ARM endpoint to be of a particular format as described [here](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#error-response-content)

**Comment by philliphoff** [comment]
So far I've only ever gotten JSON from the production Azure endpoints, but I'm working with a staging endpoint that is returning plaintext for `404` responses to "get resource with name" style requests.  

I'm able to workaround it for now by adding a filter that takes the plaintext and JSON-ifies it before passing it on to the next filter.

**Comment by amarzavery** [comment]
The 404 response should also send back an error object  as per the schema defined in the previous comment. I would recommend the service to change that as it violates the guidelines.

We should also have a check in the send request method to check the type of the error before calling JSON.stringify on it.

**Comment by philliphoff** [comment]
I was able to get an explanation for the plaintext with the `404`; due to a recent rename, the endpoint was no longer on a route responsible for that error handling.

In any case, I agree that it would be good to do some content-type checking before attempting to deserialize the JSON.  I still wonder, though, whether the existing error handling is correct (as the original issue was an exception thrown *during* exception handling due to the JSON parse error).

**Comment by RikkiGibson** [comment]
It seems reasonable enough to just tack the HTTP response error body to the RestError we create instead of creating a new error about a JSON parse failure.
