### ISSUE TITLE
(azure-arm-website) - Exception: TypeError: Cannot read property 'getSites' of undefined

### ISSUE THREAD

**Issue by the1bit** [Azure/azure-sdk-for-node#5089]
Hi,

I am writing because I would like to create a JS Azure function but I am struggling due to an issue.
I use your example code from [Github](https://github.com/Azure/azure-sdk-for-node/blob/master/examples/ARM/webapp/webapp-sample.js):

```
var WebSiteManagement = require('azure-arm-website');
var webSiteClient = new WebSiteManagement(credentials, subscriptionId);

function listWebsites(callback) {
        console.log('\nListing websits in subscription : ' + subscriptionId);
        return webSiteClient.sites.getSites(resourceGroupName, null, callback);
    }
```

Error message is the following:

```
Executed 'Functions.CoreScheduler' (Failed, Id=4bcdfa48-90f4-4155-b4cd-5a00f246e8cb)
System.Private.CoreLib: Exception while executing function: Functions.CoreScheduler. System.Private.CoreLib: Result: Failure
Exception: TypeError: Cannot read property 'getSites' of undefined
Stack: TypeError: Cannot read property 'getSites' of undefined
    at listWebsites (C:\Development\functionapps\JavaScript\monitoring\modules\webapp.js:77:36)
    at C:\Development\functionapps\JavaScript\monitoring\modules\webapp.js:35:13
    at C:\Development\functionapps\JavaScript\monitoring\node_modules\async\dist\async.js:3866:24
    at replenish (C:\Development\functionapps\JavaScript\monitoring\node_modules\async\dist\async.js:998:17)
    at C:\Development\functionapps\JavaScript\monitoring\node_modules\async\dist\async.js:1002:9
    at eachOfLimit (C:\Development\functionapps\JavaScript\monitoring\node_modules\async\dist\async.js:1027:24)
    at C:\Development\functionapps\JavaScript\monitoring\node_modules\async\dist\async.js:1032:16
    at _parallel (C:\Development\functionapps\JavaScript\monitoring\node_modules\async\dist\async.js:3865:5)
    at Object.series (C:\Development\functionapps\JavaScript\monitoring\node_modules\async\dist\async.js:4721:5)
    at module.exports (C:\Development\functionapps\JavaScript\monitoring\modules\webapp.js:33:11).
```

My development environment related information:

- OS: Windows 10
- IDE: Visual Studio Code 1.35.1
- NodeJS version: v10.15.1
- NPM version: 6.4.1
- Dependencies in  package.json:
```
"azure-arm-resource": "^7.3.0",
"azure-arm-website": "^5.7.0",
"azure-common": "^0.9.20",
"ms-rest": "^2.5.1",
"ms-rest-azure": "^2.6.0"
```

Could you please help me to solve this issue?

Thank you for your help in this topic.

Best  Regards,
Tibor Kiss

**Comment by the1bit** [comment]
I have solved the issue which is a lack of documentation from your site. :-(

You had replaced the sites to webApps

**Comment by the1bit** [comment]
I solved the issue. You can find the solution in my previous comment.
