### ISSUE TITLE
Error: 401 - ExpiredToken: The token is expired on Daylight Saving Time Change

### ISSUE THREAD

**Issue by vIceBerg** [Azure/azure-sdk-for-node#5106]
Hi!

As you know, we changed the time from Daylight Saving to Normal Time in North America.

As soon as the hour passed from 1:59 to 1:00, Azure Service Bus gave me the message "Error: 401 - ExpiredToken: The token is expired"

Even if I killed my app and restart it, I got the same error.

When my computer time reached 2:00, then I was back to normal...

Should'nt Service Bus be aware of time changing? 

Thanks

```
2018-11-04T01:59:24-04:00 16540 Waiting for messages...
2018-11-04T01:00:24-05:00 16540 Waiting for messages...
2018-11-04T01:00:25-05:00 16540 ===> azure sdk RX ERROR:  { Error: 401 - ExpiredToken: The token is expired. Expiration time: '2018-11-04 05:05:25Z'. TrackingId:04fd8272-9120-4d
    at Function.ServiceClient._normalizeError (/tuxedo/cotecour/v2018-09-01/TuxedoBackend/node_modules/azure-common/lib/services/serviceclient.js:814:23)
    at ServiceBusService.ServiceClient._processResponse (/tuxedo/cotecour/v2018-09-01/TuxedoBackend/node_modules/azure-common/lib/services/serviceclient.js:455:41)
    at Request.processResponseCallback [as _callback] (/tuxedo/cotecour/v2018-09-01/TuxedoBackend/node_modules/azure-common/lib/services/serviceclient.js:213:35)
    at Request.self.callback (/tuxedo/cotecour/v2018-09-01/TuxedoBackend/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/tuxedo/cotecour/v2018-09-01/TuxedoBackend/node_modules/request/request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/tuxedo/cotecour/v2018-09-01/TuxedoBackend/node_modules/request/request.js:1083:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: '401',
  detail: 'ExpiredToken: The token is expired. Expiration time: \'2018-11-04 05:05:25Z\'. TrackingId:04fd8272-9120-4d3d-a910-31be570e105c_G12, SystemTracker:tuxedo.servicebus.wi
  statusCode: 401 }
2
```

**Comment by ramya-rao-a** [comment]
@amarzavery This looks like the issue with how expiry dates are dealt with inside of azure-common.
If we expect the same to happen in the new service bus library, then moving it to the new repo makes sense, else this is a bug fix needed in azure-common. Am I missing something?

**Comment by amarzavery** [comment]
I feel this seems to be a service side issue and not an issue with the client. If this is a client side issue then I would recommend to ensure that this doesn't happen in the new library that is developed for http based atom apis

**Comment by ramya-rao-a** [comment]
Fair point, will transfer back and loop in the service team. Thanks!
