### ISSUE TITLE
Error: credentials must be one of: ApplicationTokenCredentials, UserTokenCredentials, DeviceTokenCredentials, MSITokenCredentials

### ISSUE THREAD

**Issue by workfigure** [Azure/azure-sdk-for-node#5112]
I am following this [sample code](https://github.com/Azure-Samples/key-vault-node-quickstart) to get secret key from the azure key-vault using Azure function but I am getting this error message.
The msRestAzure.loginWithAppServiceMSI return value of type MSIAppServiceTokenCredentials and when it call client.getSecret(vaultUri, secretName, secretVersion), I am getting the error message.
Node module I am using:
"azure-keyvault": "^3.0.4",
"ms-rest-azure": "^3.0.0",

Here is the code:
return msRestAzure.loginWithAppServiceMSI({resource: 'https://vault.azure.net'})
.then((credentials) => {
const client = new KeyVault.KeyVaultClient(credentials);
return client.getSecret(vaultUri, secretName, secretVersion)
.then((result) => {
return result;
})
});

The response from the msRestAzure.loginWithAppServiceMSI
MSIAppServiceTokenCredentials {
resource: 'https://vault.azure.net',
msiEndpoint: 'http://179.16.0.6:8081/msi/token',
msiSecret: 'ABDAERDF-10ab-4fa0-8cd7-8f829dbc1fb5',
msiApiVersion: '2017-09-01'
}

Error message from client.getSecret(vaultUri, secretName, secretVersion)
2019-08-12T18:29:49.667689275Z: [INFO] Error: credentials must be one of: ApplicationTokenCredentials, UserTokenCredentials, DeviceTokenCredentials, MSITokenCredentials
2019-08-12T18:29:49.668238579Z: [INFO] �[40m�[32minfo�[39m�[22m�[49m: Host.Function.Console[0]
2019-08-12T18:29:49.668250979Z: [INFO] at KeyVaultCredentials.authenticator (/home/site/wwwroot/node_modules/azure-keyvault/node_modules/ms-rest-azure/lib/credentials/keyVaultCredentials.js:63:16)
2019-08-12T18:29:49.668255379Z: [INFO] �[40m�[32minfo�[39m�[22m�[49m: Host.Function.Console[0]
2019-08-12T18:29:49.668259179Z: [INFO] at KeyVaultCredentials.handleUnauthorized (/home/site/wwwroot/node_modules/azure-keyvault/node_modules/ms-rest-azure/lib/credentials/keyVaultCredentials.js:175:15)
2019-08-12T18:29:49.668263079Z: [INFO] �[40m�[32minfo�[39m�[22m�[49m: Host.Function.Console[0]
2019-08-12T18:29:49.668266779Z: [INFO] at nextHandler (/home/site/wwwroot/node_modules/azure-keyvault/node_modules/ms-rest-azure/lib/credentials/keyVaultCredentials.js:118:19)
2019-08-12T18:29:49.669685690Z: [INFO] �[40m�[32minfo�[39m�[22m�[49m: Host.Function.Console[0]
2019-08-12T18:29:49.669700290Z: [INFO] at Request.defaultRequest [as _callback] (/home/site/wwwroot/node_modules/ms-rest/lib/requestPipeline.js:125:16)

**Comment by michaeljqzq** [comment]
@workfigure Could you try using the following dependency? `"ms-rest-azure": "^2.6.0"`

**Comment by workfigure** [comment]
@michaeljqzq thanks for the respond and it did not fix it.

**Comment by workfigure** [comment]
I found out temporary solution. 
The problem is that 
at line 54-68 of file /node_modules/azure-keyvault/node_modules/ms-rest-azure/lib/credentials/keyVaultCredentials.js, there is type comparison and it is the one causing the error. The object I am getting from the call msRestAzure.loginWithAppServiceMSI is MSIAppServiceTokenCredentials and I created this object by require('ms-rest-azure') but the object the azure-keyvault is comparing using the instance it loads by require('ms-rest-azure'). So the instance I created is not the same type of the azure-keyvault created even-if the node module is the same copy.

Here is the temporary solution to get key/secret from key vault.
First expose the msRestAzure from  the azure-keyvault node module. To do that update the node_modules/azure-keyvault/lib/keyVault.js file with this one line code.
module.exports.msRestAzure = msRestAzure;


const KeyVault = require('azure-keyvault');
var getKeyValue = async (secretName, secretVersion)=>{
    // The ms-rest-azure library allows us to login with MSI by providing the resource name. In this case the resource is Key Vault.
    return **KeyVault.msRestAzure.loginWithAppServiceMSI**({resource: 'https://vault.azure.net'})
    .then((credentials) => {
        var vaultUri = "https://<ur key vault name>.vault.azure.net/";
        const client = new KeyVault.KeyVaultClient(credentials);

        return client.getSecret(vaultUri, secretName, secretVersion)
        .then((result) => {
            return result.value;
        })
        .catch((err)=>{
            console.log(err);
            return err;
        });
    })
    .catch((err)=>{
        console.log(err);
        return err;
    });
};

**Comment by robwadsworth1992** [comment]
I am also facing this issue.
My current solution works only because a single version of ms-rest-azure is installed within my project. If ms-rest-azure is included as a child package of both azure-keyvault and _my-other-installed-package_ then creating the credentials within my-other-installed-package will not create a object of they type expected within azure-keyvault.

**Comment by ned1313** [comment]
Also facing this issue on App Service deployment.  Resulting error in console logging:

`(node:3544) UnhandledPromiseRejectionWarning: Error: credentials must be one of: ApplicationTokenCredentials, UserTokenCredentials, DeviceTokenCredentials, MSITokenCredentials
    at KeyVaultCredentials.authenticator (D:\home\site\wwwroot\node_modules\azure-keyvault\node_modules\ms-rest-azure\lib\credentials\keyVaultCredentials.js:63:16)
    at KeyVaultCredentials.handleUnauthorized (D:\home\site\wwwroot\node_modules\azure-keyvault\node_modules\ms-rest-azure\lib\credentials\keyVaultCredentials.js:175:15)
    at nextHandler (D:\home\site\wwwroot\node_modules\azure-keyvault\node_modules\ms-rest-azure\lib\credentials\keyVaultCredentials.js:118:19)
    at Request.defaultRequest [as _callback] (D:\home\site\wwwroot\node_modules\ms-rest\lib\requestPipeline.js:125:16)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:194:15)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
(node:3544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`

Credential info is as follows:
credential msiApiVersion: 2017-09-01
credential msiEndpoin:t http://127.0.0.1:41397/MSI/token/
credential msiSecret: XXXXXXXXXXXXXXXXXXXXXXXX
credential resource: https://vault.azure.net
vaultUri is https://XXXXX.vault.azure.net/

**Comment by michaeljqzq** [comment]
@workfigure, @robwadsworth1992 , @ned1313 Actually for the keyvault service, the node SDK is going to be deprecated and won't have new feature and releases. Instead, the new versions are released here: https://www.npmjs.com/package/@azure/keyvault-secrets https://www.npmjs.com/package/@azure/keyvault-keys . You can have a try with the new SDK. And feel free to give feedback if that won't work or have further issues.

**Comment by workfigure** [comment]
@michaeljqzq Thanks for the update. I will try it.

**Comment by workfigure** [comment]
@michaeljqzq, @robwadsworth1992 , @ned1313  Tried the module @azure/keyvault-secrets and it works as expected. Thanks again!

**Comment by sprour** [comment]
I had the same issue. So, first remove package-lock.json and node_modules. Then install again with "ms-rest-azure": "^2.6.0"
