### ISSUE TITLE
Accessing Azure Media Services V3 API with Nodejs, "Could not determine tenant error"

### ISSUE THREAD

**Issue by Haga14** [Azure/azure-sdk-for-node#5121]
I'm connecting to AZ MS V3 API with Nodejs following the instructions found here: 
https://docs.microsoft.com/en-us/azure/media-services/latest/configure-connect-nodejs-howto

Below is my code: 

```
'use strict';
require('dotenv').config()

const MediaServices = require('azure-arm-mediaservices');
const msRestAzure = require('ms-rest-azure');
const msRest = require('ms-rest');
const azureStorage = require('azure-storage');

// endpoint config
// make sure your URL values end with '/'
const armAadAudience = process.env.armAadAudience;
const aadEndpoint = process.env.aadEndpoint;
const armEndpoint = process.env.armEndpoint;
const subscriptionId = process.env.subscriptionId;
const accountName = process.env.accountName;
const region = process.env.region;
const aadClientId = process.env.aadClientId;
const aadSecret = process.env.aadSecret;
const aadTenantId = process.env.aadTenantId;
const resourceGroup = process.env.resourceGroup;

let azureMediaServicesClient;

///////////////////////////////////////////
//     Entrypoint for sample script      //
///////////////////////////////////////////

msRestAzure.loginWithServicePrincipalSecret(aadClientId, aadSecret, aadTenantId, {
  environment: {
    activeDirectoryResourceId: armAadAudience,
    resourceManagerEndpointUrl: armEndpoint,
    activeDirectoryEndpointUrl: aadEndpoint
  }
}, async function(err, credentials, subscriptions) {
    if (err) return console.log(err);
    azureMediaServicesClient = new MediaServices(credentials, subscriptionId, armEndpoint, { noRetryPolicy: true });
    
    console.log("connected");

});
```
When I run this code, I get the following error:

```

Error: Could not determine tenant.
    at Authority._parseAuthority (Workspace/Dhagamaal/back/test/node_modules/adal-node/lib/authority.js:115:11)
    at new Authority (/Workspace/Dhagamaal/back/test/node_modules/adal-node/lib/authority.js:47:8)
    at new AuthenticationContext (//Workspace/Dhagamaal/back/test/node_modules/adal-node/lib/authentication-context.js:92:21)
    at new ApplicationTokenCredentials (Workspace/Dhagamaal/back/test/node_modules/ms-rest-azure/lib/credentials/applicationTokenCredentials.js:115:20)
    at _withServicePrincipalSecret (/Workspace/Dhagamaal/back/test/node_modules/ms-rest-azure/lib/login.js:434:13)
    at Object.withServicePrincipalSecret [as loginWithServicePrincipalSecret] (/Workspace/Dhagamaal/back/test/node_modules/ms-rest-azure/lib/login.js:493:12)
    at Object.<anonymous> (Workspace/Dhagamaal/back/test/connect.js:28:13)
```

**Comment by michaeljqzq** [comment]
Could you provide the version of the package `azure-arm-mediaservices` ?

**Comment by Haga14** [comment]
@michaeljqzq Below is my package json

````
  "dependencies": {
    "azure-arm-mediaservices": "^4.1.0",
    "azure-storage": "^2.8.0",
    "ms-rest": "^2.3.3",
    "ms-rest-azure": "^2.5.5",
    "dotenv": "^8.1.0"
  }

````

**Comment by michaeljqzq** [comment]
Hi @Haga14 , the node library is going to be deprecated. You can try the [JS SDK](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/mediaservices/arm-mediaservices) and give furthur feedback

**Comment by Haga14** [comment]
@michaeljqzq I've seen that, but there's no media services specific documentation for that SDK,  more accurately, I haven't found anything

**Comment by ruowan** [comment]
Hi @Haga14 https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/mediaservices/arm-mediaservices. This doc may help you.

**Comment by ramya-rao-a** [comment]
@ruowan, @michaeljqzq, @qiaozha Can we have this issue closed?

**Comment by ramya-rao-a** [comment]
@Haga14 Please try out the new [@azure/arm-mediaservices](https://www.npmjs.com/package/@azure/arm-mediaservices). If you see any issues with the newer package, please log an issue at https://github.com/azure/azure-sdk-for-js
